AGPU_WEB/Controllers/AGPUController.cs
using AGPU_WEB.Models;
using AGPU_WEB.Models.DTO;
using AGPU_WEB.Services.IServices;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AGPU_WEB.Controllers
{
    public class AGPUController : Controller
    {
        private readonly IAGPUService _agpuService;
        private readonly IMapper _mapper;
        private readonly ILogger<AGPUController> _logger;
        public AGPUController(IAGPUService aGPUService, IMapper mapper, ILogger<AGPUController> logger)
        {
            _agpuService = aGPUService;
            _mapper = mapper;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AGPUCreateDTO dto)
        {
            if (ModelState.IsValid)
            {
                var response = await _agpuService.AddAsync<APIResponse>(dto);
                if (response != null && response.IsSuccess == true)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(dto);
        }
        
        public async Task<IActionResult> Edit (int id)
        {
            var response = await _agpuService.GetAsync<APIResponse>(id); // get the agpu based on id

            if(response != null && response.IsSuccess == true)
            {
                var result = JsonConvert.DeserializeObject<AGPUDTO>(Convert.ToString(response.Result)); //the result is of form agpudto
                var mappedResult = _mapper.Map<AGPUUpdateDTO>(result);
                return View(mappedResult);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (AGPUUpdateDTO dto)
        {
            if (ModelState.IsValid)
            {
                var response = await _agpuService.UpdateAsync<APIResponse>(dto);
                if(response!=null && response.IsSuccess == true)
                {
					return RedirectToAction(nameof(Index));
				}
                return NotFound();
            }
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            // Log the anti-forgery token from the request headers
            //var token = Request.Headers["RequestVerificationToken"].ToString();
            //_logger.LogInformation("Anti-Forgery Token from request: {Token}", token);

            var response = _agpuService.GetAsync<APIResponse>(id);

            if(response != null)
            {
                var delete =_agpuService.RemoveAsync<APIResponse>(id);

                if(delete != null)
                {
                    return RedirectToAction(nameof(Index));
				}
            }
            return NotFound();
		}

	}
}

AGPU_WEB/Views/AGPU/Create.cshtml
@model AGPU_WEB.Models.DTO.AGPUCreateDTO

<form asp-action="Create">
	<br/>
	<div class="container border p-3">
		<h1 class="text-primary">Create New AGPU</h1>
		<hr/>

		<div class="row">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			@* //name *@

			<div class="col-2">
				<label asp-for="Name" class="form-label pt-2 pb-3"></label>
			</div>
			<div class="col-10">
				<input asp-for="Name" class="form-control pt-2" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>

			@* brand *@

			<div class="col-2">
				<label asp-for="Brand" class="form-label pt-2 pb-3"></label>
			</div>
			<div class="col-10">
				<input asp-for="Brand" class="form-control pt-2" />
				<span asp-validation-for="Brand" class="text-danger"></span>
			</div>

			@* model *@

			<div class="col-2">
				<label asp-for="Model" class="form-label pt-2 pb-3"></label>
			</div>
			<div class="col-10">
				<input asp-for="Model" class="form-control pt-2" />
				<span asp-validation-for="Model" class="text-danger"></span>
			</div>

			@* averageBench *@

			<div class="col-2">
				<label asp-for="AverageBenchPercentage" class="form-label pt-2 pb-3">Average Bench</label>
			</div>
			<div class="col-10">
				<input asp-for="AverageBenchPercentage" class="form-control pt-2" />
				<span asp-validation-for="AverageBenchPercentage" class="text-danger"></span>
			</div>

			@* valuePercentage *@
			<div class="col-2">
				<label asp-for="ValuePercentage" class="form-label pt-2 pb-3">Value</label>
			</div>
			<div class="col-10">
				<input asp-for="ValuePercentage" class="form-control pt-2" />
				<span asp-validation-for="ValuePercentage" class="text-danger"></span>
			</div>

			@* ReleaseDate *@

			<div class="col-2">
				<label asp-for="ReleaseDate" class="form-label pt-2 pb-3">Releasae Date</label>
			</div>
			<div class="col-10">
				<input asp-for="ReleaseDate" class="form-control pt-2" type="date" />
				<span asp-validation-for="ReleaseDate" class="text-danger"></span>
			</div>

			@* Price *@

			<div class="col-2">
				<label asp-for="Price" class="form-label pt-2 pb-3"></label>
			</div>
			<div class="col-10">
				<input asp-for="Price" class="form-control pt-2" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>

			@* imageUrl *@

			<div class="col-2">
				<label asp-for="Images" class="form-label pt-2 pb-3">Image Url</label>
			</div>
			<div class="col-10">
				<input asp-for="Images" class="form-control pt-2" />
				<span asp-validation-for="Images" class="text-danger"></span>
			</div>

			@* backtolist *@

			<div class="col-5 offset-2 pt-2">
				<a asp-controller="AGPU" asp-action="Index" class="btn btn-primary form-control" >Back to List</a>
			</div>

			@* submitbutton *@

			<div class="col-5 pt-2">
				<input type="submit" value="Create" class="btn btn-success form-control" />
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

AGPU_WEB/Views/AGPU/Edit.cshtml
@model AGPU_WEB.Models.DTO.AGPUUpdateDTO
<form asp-action="Edit">
	<br/>
 <div class="Container border p-3">
	<h1 class="text-primary">Edit AGPU</h1>
	<hr/>
	<input hidden asp-for="Id" />
	<div class="row">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>

		@* //name *@

		<div class="col-2">
			<label asp-for="Name" class="form-label pt-2 pb-3"></label>
		</div>
		<div class="col-10">
			<input asp-for="Name" class="form-control pt-2" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>

		@* brand *@

		<div class="col-2">
			<label asp-for="Brand" class="form-label pt-2 pb-3"></label>
		</div>
		<div class="col-10">
			<input asp-for="Brand" class="form-control pt-2" />
			<span asp-validation-for="Brand" class="text-danger"></span>
		</div>


		@* model *@

		<div class="col-2">
			<label asp-for="Model" class="form-label pt-2 pb-3"></label>
		</div>
		<div class="col-10">
			<input asp-for="Model" class="form-control pt-2" />
			<span asp-validation-for="Model" class="text-danger"></span>
		</div>

		@* averageBench *@

		<div class="col-2">
			<label asp-for="AverageBenchPercentage" class="form-label pt-2 pb-3">Average Bench</label>
		</div>
		<div class="col-10">
			<input asp-for="AverageBenchPercentage" class="form-control pt-2" />
			<span asp-validation-for="AverageBenchPercentage" class="text-danger"></span>
		</div>

		@* valuePercentage *@
		<div class="col-2">
			<label asp-for="ValuePercentage" class="form-label pt-2 pb-3">Value</label>
		</div>
		<div class="col-10">
			<input asp-for="ValuePercentage" class="form-control pt-2" />
			<span asp-validation-for="ValuePercentage" class="text-danger"></span>
		</div>

		@* ReleaseDate *@

		<div class="col-2">
			<label asp-for="ReleaseDate" class="form-label pt-2 pb-3">Releasae Date</label>
		</div>
		<div class="col-10">
			<input asp-for="ReleaseDate" class="form-control pt-2" type="date" />
			<span asp-validation-for="ReleaseDate" class="text-danger"></span>
		</div>

		@* Price *@

		<div class="col-2">
			<label asp-for="Price" class="form-label pt-2 pb-3"></label>
		</div>
		<div class="col-10">
			<input asp-for="Price" class="form-control pt-2" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>

		@* imageUrl *@

		<div class="col-2">
			<label asp-for="Images" class="form-label pt-2 pb-3">Image Url</label>
		</div>
			<div class="col-10">
				@if (Model.Images != null && Model.Images.Any())
				{
					<input asp-for="Images" type="text" class="form-control pt-2" value="@Model.Images.First()"/>
				}
				else
				{
					<input type="text" class="form-control pt-2" value="No Image URL"/>
				}
				<span asp-validation-for="Images" class="text-danger"></span>
			</div>

		@* backtolist *@

		<div class="col-5 offset-2 pt-2">
			<a asp-controller="AGPU" asp-action="Index" class="btn btn-primary form-control">Back to List</a>
		</div>

		@* submitbutton *@

		<div class="col-5 pt-2">
			<input type="submit" value="Update" class="btn btn-success form-control" />
		</div>
	</div>
 </div>
</form>

@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

AGPU_WEB/Views/AGPU/Index.cshtml
@using System.Globalization
@* @model IEnumerable<AGPU_WEB.Models.DTO.AGPUDTO> *@
<form id="deleteAGPUForm" method="post">
	@Html.AntiForgeryToken()
</form>

@{
	ViewData["Title"] = "AGPU List";
}
<br />

<div class="container p-4 border">
	<div class="row pb-2"> @* for header *@
		<div class="col">
			<h1 class="text-primary">AGPU List</h1>
		</div>
		<div class="col text-end pt-1">
			<a asp-controller="AGPU" asp-action="Create" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill" style="margin-right:5px"></i>Create New AGPU</a>
		</div>
	</div>

	@* table *@

	<table id="AGPUListControlPanel" class="table table-bordered table-striped" style="width:100%">
		<thead>
			<tr>
				<th>
					Name
				</th>
				<th>
					Brand
				</th>
				<th>
					Model
				</th>
				<th>
					Average Bench
				</th>
				<th>
					Value
				</th>
				<th>
					Price
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			
		</tbody>
	</table>

</div>

@section Scripts{
	<script src="~/js/AGPUListControlPanel.js"></script>
}